home/urls.py
"""
@author: GZP
@contact: t: 449336625@qq.com
@file: urls.py
@time: 2018/8/15 0015 15:33
"""

from django.conf.urls import url

from home import views

urlpatterns = [
    url('index/$', views.index, name="index"),
    url('map/$', views.baidu_map, name="map"),
    url('contact/$', views.contact, name="contact"),
    # url('galleries/$', views.GalleryListView.as_view(), name="galleries"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^home/', include("home.urls", namespace="home")),
                  url(r'^message/', include("message.urls", namespace="message")),
                  url(r'^photo/', include("photo.urls", namespace="photo")),
                  url(r'^users/', include("users.urls", namespace="users")),
                  url(r'^users/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
"""
@author: GZP
@contact: 449336625@qq.com
@file: urls.py
@time: 2018/9/17 0017 9:32
"""
from django.conf.urls import url

from photo import views

urlpatterns = [
    # 相册列表
    url(r'^albums/$', views.PhotoAlbumListView.as_view(), name="albums"),
    # 相册详情列表
    url(r'^albums/(?P<albums_id>\d+)/', views.PhotoAlbumDetailView.as_view(), name="albums_detail"),
    # 照片上传的连接(个人使用)
    url(r'^uploads/$', views.PhotoView.as_view(), name="uploads"),
]

photo/models.py
import time
import uuid
import os

from django.db import models


# class Album(models.Model):
#     name = models.CharField(max_length=16, verbose_name="类别")
#
#     def __str__(self):
#         return self.name


class Album(models.Model):
    name = models.CharField(max_length=24, verbose_name="相册名称")
    desc = models.CharField(max_length=128, verbose_name="相册描述")
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "相册"
        verbose_name_plural = "相册"

    def __str__(self):
        return self.name


def photo_directory_path(instance, filename):
    # instance代表当前的Photo实例
    photo_suffix = filename.split(".")[-1]
    # filename = "{}.{}".format(uuid.uuid4().hex[:8], photo_suffix)  # 随机文件名(使用uuid)
    filename = "{}.{}".format(uuid.uuid4().hex[:4] + str(int(time.time() * 1000)), photo_suffix)  # 随机文件名(使用uuid + 时间戳)
    # 上传路径, eg: albums\1\7eee24f4.png, 这也是存储在数据库的数据
    upload_to = os.path.join("albums", str(instance.album.pk), filename)
    return upload_to


class Photo(models.Model):
    name = models.CharField(max_length=32, verbose_name="照片名称", blank=True, null=True)
    desc = models.CharField(max_length=64, verbose_name="照片描述", blank=True, null=True)
    img = models.ImageField(upload_to=photo_directory_path, verbose_name="照片")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="上传时间")
    uploader = models.CharField(max_length=16, null=True, blank=True, verbose_name="上传者")
    album = models.ForeignKey(Album, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="所属相册")

    class Meta:
        verbose_name = "照片"
        verbose_name_plural = "照片"

    def __str__(self):
        return self.name or self.pk

photo/forms.py
"""
@author: GZP
@contact: 449336625@qq.com
@file: form.py
@time: 2018/9/17 0017 15:16
"""
from django import forms

from photo.models import Photo, Album


class PhotoForm(forms.Form):
    # name = forms.CharField(label="照片名称")
    img = forms.ImageField(label="上传照片", widget=forms.FileInput(attrs={"multiple": "multiple"}))  # 仍然有是是否相片文件的校验
    album = forms.ModelChoiceField(label="所属相册", queryset=Album.objects.all(), required=True)



photo/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core import paginator

from photo.forms import PhotoForm
from photo import models
from common import utils


# 相簿列表视图
class PhotoAlbumListView(ListView):
    model = models.Album
    template_name = "photo/album_list.html"

    def get_context_data(self, **kwargs):
        """
        重写方法, 实现对相册列表分行
        """
        context = super(PhotoAlbumListView, self).get_context_data(**kwargs)
        album_list = self.get_queryset()
        # 3个一组, 根据组数组装二维数组
        group_nums = len(album_list) // 3 if len(album_list) % 3 == 0 else len(album_list) // 3 + 1
        ret_list = [[] for _ in range(group_nums)]
        # 开始分组
        for i, album in enumerate(album_list, start=0):
            ret_list[i // 3].append(album)
        album_list = ret_list
        context.update({"album_list": album_list})
        return context


# 图片上传视图
class PhotoView(View):
    @method_decorator(login_required)
    def get(self, request):
        context = {"form": PhotoForm()}
        return render(request, "photo/photo_upload.html", context=context)

    @method_decorator(login_required)
    def post(self, request):
        form = PhotoForm(request.POST, request.FILES)
        instance_list = []
        if form.is_valid():
            # 检验成功，都为图片类型
            uploader = request.user.username
            img_files = request.FILES.getlist("img")
            # 因为不是Model, 没有save方法, 要手动遍历保存为实例
            for index, img_file in enumerate(img_files, 1):
                # 因为模型里自定义了路径, 所以这里直接保存实例就可以了
                album = form.cleaned_data.get("album")
                name = ''.join(reversed(list(''.join(reversed(list(img_file.name)))[:30])))
                photo = models.Photo(name=name, img=img_file, album=album, uploader=uploader)
                photo.save()
                instance_list.append(photo)
        else:
            # 检验不成功, 即有非图片文件
            pass

        # 3个一组, 根据组数组装二维数组
        group_nums = len(instance_list) // 3 if len(instance_list) % 3 == 0 else len(instance_list) // 3 + 1
        ret_list = [[] for _ in range(group_nums)]
        # 开始分组
        for i, instance in enumerate(instance_list, start=0):
            ret_list[i // 3].append(instance)

        context = {"form": form, "instance_list": instance_list, "ret_list": ret_list}
        return render(request, "photo/photo_upload.html", context=context)


# 相簿详情视图
class PhotoAlbumDetailView(View):
    def get(self, request, albums_id):
        album = models.Album.objects.get(id=albums_id)
        photos = album.photo_set.all()
        photo_sum = photos.count()

        # 分页
        page = int(request.GET.get('page', 1))
        per_page = int(request.GET.get('per_page', 9))
        paginater = paginator.Paginator(object_list=photos, per_page=per_page)
        try:
            page_obj = paginater.page(page)
        except paginator.PageNotAnInteger:
            page_obj = paginater.page(1)  # 首次进入给第一页
            page = 1
        except paginator.EmptyPage:
            page_obj = paginater.page(paginater.num_pages)  # 空页给最后一页
            page = paginater.num_pages
        start, end = utils.custom_paginator(current_page=int(page), total_pages=paginater.num_pages, max_page=10)

        context = {"page_obj": page_obj, "page": page, "page_range": range(int(start), int(end) + 1),
                   "per_page": per_page, "total": paginater.count, "is_paginated": page_obj.has_other_pages()}
        return render(request, "photo/album_detail.html", context=context)

templates/photo/album_detail.html
{% extends 'master.html' %}
{% load static %}

{% block head_css %}
    <!-- Custom styles for this template 自定义修改 -->
    <link href="/static/home/css/carousel4contact.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'photo/album_detail/touchTouch.css' %}">
    <!-- 网页的样式框架, 包括页面照片的布局container, row, grid的样式, view more的上滑动画-->
    <link rel="stylesheet" href="{% static 'photo/album_detail/style.css' %}">

    <!-- 调整分页标签的位置 -->
    <link rel="stylesheet" href="{% static 'photo/album_detail/custom_page_tag.css' %}">
{% endblock %}

{% block carousel %}
{% endblock %}

{% block wholecontents %}
    <!--=====================  Content(定义背景图)  ======================-->
    <section id="content" class="gallery">
        <div class="container2">
            <div class="row">
                <div class="grid_12">
                    <h2>Gallery</h2>
                </div>
                {% for photo in page_obj %}
                    <div class="grid_4">
                        <div class="box">
                            <a href="{{ photo.img.url }}" class="gall_item" style="text-align: center;">
                                <img src="{{ photo.img.url }}" alt="big1.jpg"><span></span>
                            </a>
                            <div class="box_bot">
                                <div class="box_bot_title">照片名</div>
                                <p>照片描述</p>
                                <a href="#" class="btn">more</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                {% include 'snippet/page_snippet.html' %}
            </div>
        </div>
    </section>
{% endblock %}

{% block tail_scripts %}
    <script src="/static/common/js/jquery-1.12.4.min.js"></script>
    <script src="/static/common/js/jquery-migrate-1.1.1.js"></script>
    <script src="/static/common/js/jquery.easing.1.3.js"></script>
    <script src="/static/photo/js/script.js"></script>
    <script src="/static/common/js/superfish.js"></script>  <!-- jQuery菜单插件superfish -->
    <script src="/static/common/js/jquery.equalheights.js"></script>  <!-- jQuery 自动等高插件 -->
    <script src="/static/common/js/jquery.mobilemenu.js"></script>  <!-- jQuery Mobile 表单选择菜单 -->

    <script src="/static/photo/js/tmStickUp.js"></script>  <!--  -->
    <script src="/static/common/js/jquery.ui.totop.js"></script>
    <script src="/static/photo/js/touchTouch.jquery.js"></script>  <!-- 实现悬浮显示图片详情 -->
    <script>
        $(window).load(function () {
            $().UItoTop({easingType: 'easeOutQuart'});
            $('.gallery .gall_item').touchTouch();

            // 微调初始化的高度
            var boxes = $(".box");
            var h = boxes.width() * 9 / 16 + 68;
            boxes.css({
                height: h,
            });

            {# 图片所在box的高度随窗口自适应#}
            $(window).resize(function () {
                var box = $(".box");
                var w = box.width();
                var h = w * 9 / 16 + 68;
                box.css({
                    height: h,
                });
            });

            // 自定义的hover响应
            boxes.children(".gall_item").hover(
                function () {
                    var box = $(this).parent(".box");
                    var h = (box.height() - 79) / 2;
                    var pos = "center " + h.toString() + "px";
                    box.children(".gall_item").children("span").css({backgroundPosition: pos});
                }, function () {
                    var box = $(this).parent(".box");
                    var h = box.height() / 2;
                    box.children(".gall_item").children("span").css({backgroundPosition: "center -100px"});
                }
            );
        });
    </script>
{% endblock %}

templates/photo/album_list.html
{% extends "master.html" %}

{% block title %}相册{% endblock %}

{% block head_css %}
    <!-- 对一些标签样式额外做一些修改 -->
    <link href="/static/photo/css/carousel4photo.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/photo/css/jumbotron_custom.css" rel="stylesheet">

    <style>
    /*自定义减少jumbotron类的高度*/
    .jumbotron{
        opacity: 0;
        height: 0;
        padding-top: 0;
        padding-bottom: 0;
    }
    </style>
{% endblock %}

{% block carousel %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-color: initial;">
            </div>
        </div>
    </div><!-- /.carousel -->
{% endblock %}

{% block wholecontents %}
    <!-- 将页面的其余部分包装在另一个container中，以将所有内容居中。 -->
    <div class="container">
        <div class="jumbotron">
{#            <h1>相册列表</h1>#}
{#            <p class="lead">下面是一堆相册</p>#}
        </div>
    </div>
    <div class="container marketing">
        <!-- Three columns of text below the carousel -->
        {% for row in album_list %}
            <div class="row">
                {% for album in row %}
                    <div class="col-lg-4">
                        <img class="img-circle"
                             src="{{ album.photo_set.first.img.url }}"
                             alt="Generic placeholder image" width="140" height="140">
                        <h2>{{ album.name }}</h2>
                        <p>{{ album.desc }}</p>
                        <p>最近更新：{{ album.updated_time }}</p>
                        <p><a class="btn btn-default" href="{% url 'photo:albums_detail' album.pk %}" role="button">View details &raquo;</a></p>
                    </div><!-- /.col-lg-4 -->
                {% endfor %}
            </div>
        {% endfor %}
    </div><!-- /.container -->
{% endblock %}

{% block tail_scripts %}
{% endblock %}

templates/photo/photo_upload.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>图片上传</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container" style="margin: 20px auto;">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">上传</button>
    </form>
</div>


{# 罗列出已经上传的文件/图片（公共代码）#}
{% if instance_list %}
    <div class="container">
        <table id="gallery" class="table table-bordered">
            <thead>
            <tr>
                <th>Photo</th>
            </tr>
            </thead>
            <tbody>
            {% for photo in instance_list %}
                <tr>
                    <td><a href="{{ photo.img.url }}">{{ photo.img.name }} | {{ photo.name }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container">
        {% for row in ret_list %}
            <div class="row">
                {% for photo in row %}
                    <div class="col-md-4" style="margin: 20px auto;">
                        <img src="{{ photo.img.url }}" height="100%" width="100%" alt="{{ photo.name }}">
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endif %}


<script src="/static/common/js/jquery-1.12.4.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
</body>
</html>