home/urls.py
"""
@author: GZP
@contact: t: 449336625@qq.com
@file: urls.py
@time: 2018/8/15 0015 15:33
"""

from django.conf.urls import url

from home import views

urlpatterns = [
    url('index/$', views.index, name="index"),
    url('map/$', views.baidu_map, name="map"),
    url('contact/$', views.contact, name="contact"),
    # url('galleries/$', views.GalleryListView.as_view(), name="galleries"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^home/', include("home.urls", namespace="home")),
                  url(r'^message/', include("message.urls", namespace="message")),
                  url(r'^photo/', include("photo.urls", namespace="photo")),
                  url(r'^users/', include("users.urls", namespace="users")),
                  url(r'^users/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""
@author: GZP
@contact: 449336625@qq.com
@file: urls.py
@time: 2018/8/25 17:56
"""

from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^password_change/$', views.PasswordChangeCustomView.as_view(), name='password_change'),  # 修改密码
    url(r'^password_reset/$', views.PasswordResetCustomView.as_view(), name='password_reset'),  # 重置密码

    url(r'^user_info/$', views.UserInfoView.as_view(), name='user_info'),  # 个人信息
    url(r'^user_headshot/$', views.UserHeadshotView.as_view(), name='user_headshot'),  # 个人信息
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import get_object_or_404

from message.models import LeaveMessage


class User(AbstractUser):
    phone = models.CharField(max_length=16, verbose_name='手机号码')
    headshot = models.ImageField(upload_to='avatar/%Y/%m/%d', default="alien.jpg", verbose_name='头像')
    password = models.CharField(max_length=128, verbose_name='密码', default='Changeme123')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='注册时间')

    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        return self.username

    # 判断是否点赞
    def is_favorites(self, msgid):
        item = self.like_msg_set.filter(pk=msgid)
        # print(msgid, item)
        if self.like_msg_set.filter(pk=msgid):
            # 已对该留言点赞
            # print("已对该留言点赞")
            return True
        else:
            # 未对该留言点赞
            # print("未对该留言点赞")
            return False

    # 建立点赞
    def add_favorites(self, msgid):
        # print("那就建立点赞关系")
        msg = get_object_or_404(klass=LeaveMessage, id=msgid)
        self.like_msg_set.add(msg)

    # 取消点赞
    def cancel_favorites(self, msgid):
        # print("那就取消点赞")
        msg = get_object_or_404(klass=LeaveMessage, id=msgid)
        self.like_msg_set.remove(msg)

    # 获取已点赞的留言id列表
    def get_favorites_id_list(self):
        id_list = []
        likes = self.like_msg_set.all()
        for msg_obj in likes:
            id_list.append(msg_obj.id)
        return id_list

users/forms.py
"""
@author: GZP
@contact: 449336625@qq.com
@file: forms.py
@time: 2018/8/25 22:49
"""
import re

from django.contrib.auth.forms import UserCreationForm, forms, AuthenticationForm, PasswordResetForm

from users.models import User


class RegisterModelForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password 1",
        widget=forms.PasswordInput,
        required=False,
    )
    password2 = forms.CharField(
        label="Password 2",
        widget=forms.PasswordInput,
        required=False,
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'phone')
        widgets = {
            'username': forms.widgets.TextInput(attrs={'class': 'form-control',
                                                       'placeholder': '烦请输入真实姓名'}),
            'phone': forms.widgets.NumberInput(attrs={'class': 'form-control',
                                                      'placeholder': '请输入11位手机号码'})
        }

    def clean_password2(self):
        # 覆写该方法, 为了不走注册时密码校验
        # make_random_password
        return "我也不知道填什么"

    def clean_phone(self):
        # 从cleaned_data中取出我们需要的数据
        phone = self.cleaned_data.get('phone')
        if not phone:
            raise forms.ValidationError('您并未输入电话号码')
        if not len(phone) == 11:
            # 号码长度不正确
            raise forms.ValidationError("该手机号码位数不正确")
        phone_re = "1[3,4,5,7,8]\d{9}"
        if not re.match(phone_re, phone):
            # 号码不是合法号码
            raise forms.ValidationError("您输入的手机号码不合法")
        return phone

    def save(self, commit=True):
        """
        重写方法, 设置默认密码。（如果没有给定密码，密码就会被设置成不使用，同用set_unusable_password()。
        设置user无密码。 不同于密码为空，如果使用 check_password()，则不会返回True。）
        """
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password("0000")  # 设置默认密码为 0000
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    # 直接继承默认的验证表单类
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        # 后端验证是否有数据
        if not (username and password):
            raise forms.ValidationError('用户名或密码为空')
        # 调用方法, 验证密码, 成功返回用户
        self.user_cache = self.authenticate(self.request, username=username, password=password)
        return self.cleaned_data

    def authenticate(self, request, username, password=None, **kwargs):
        # 重写authenticate 方法, 跳过Django自带的权限验证
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise forms.ValidationError('用户名或密码错误')
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user
            else:
                raise forms.ValidationError("用户名或密码错误")

    def user_can_authenticate(self, user):
        """
        验证用户是否激活, 未激活不能登录
        """
        is_active = getattr(user, 'is_active', None)
        return is_active or is_active is None


class PasswordResetCustomEmailForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email):
            # 该邮箱未注册
            raise forms.ValidationError("该邮箱未注册")
        # 必须返回email, 不然email就会变为None
        return email

users/views.py
import base64
import json
import os
import time
import uuid

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import SuccessURLAllowedHostsMixin, PasswordChangeView, PasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.db.models.fields.files import ImageFieldFile
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, resolve_url
from django.shortcuts import redirect, reverse
from django.contrib.auth import login as auth_login, REDIRECT_FIELD_NAME
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView

from django.conf import settings
from users.forms import RegisterModelForm, LoginForm, PasswordResetCustomEmailForm


def register(request):
    form = RegisterModelForm()
    # 获取跳转地址
    redirect_to = request.POST.get('next', request.GET.get('next', None))
    # 判断是什么方法提交
    if request.method == 'POST':
        # 先生成表单
        form = RegisterModelForm(request.POST)
        # 判断表单数据是否合法
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # 注册成功后直接登录
            # 判断是否存在redirect_to
            if redirect_to:
                return redirect(redirect_to)
            else:
                # 没有就重定向至首页
                return redirect(reverse('home:index'))
    # 验证不合法或者不是POST提交
    return render(request, 'users/register.html', {'form': form, 'next': redirect_to})


class LoginView(SuccessURLAllowedHostsMixin, FormView):
    """
    Displays the login form and handles the login action.
    """
    form_class = LoginForm  # 改成自定义的Form
    authentication_form = None
    redirect_field_name = REDIRECT_FIELD_NAME  # 'next'
    template_name = 'registration/login.html'
    redirect_authenticated_user = True
    extra_context = None

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        """
            Django拓展该方法是对已通过用户验证的访问进行重定向。例如：先前已登录且没有注销和清除COOKIES，
        当访问/user/login/时，若设置redirect_authenticated_user = True， 则会将用户请求重定向至next或者
        setting.LOGIN_REDIRECT_URL
        """
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_redirect_url(self):
        """如果存在next=xxxxx, 返回用户发起的该重定向 URL if it's safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

    def get_form_class(self):
        return self.authentication_form or self.form_class

    def get_form_kwargs(self):
        kwargs = super(LoginView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        current_site = get_current_site(self.request)
        context.update({
            self.redirect_field_name: self.get_redirect_url(),
            'site': current_site,  # TCP/IP 地址
            'site_name': current_site.name,  # TCP/IP 地址
        })
        if self.extra_context is not None:
            context.update(self.extra_context)
        return context


class PasswordChangeCustomView(PasswordChangeView):
    # 继承DJango封装好的PasswordChangeView

    def get_success_url(self):
        # 重写方法, 指定页面跳转逻辑
        url = self.get_redirect_url()
        return url or reverse("password_change_done")

    def get_redirect_url(self):
        # 获取重定向url
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', ''))
        # 检查url是否安全
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts={self.request.get_host()},
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else None


# 继承PasswordResetView类, 为了使用自定义的发邮箱模版
class PasswordResetCustomView(PasswordResetView):
    # 邮件内容的模板(注释了才是使用默认)
    # email_template_name = 'registration/password_reset_email.html'

    # 邮件主题的模板(注释了才是使用默认)
    # subject_template_name = 'registration/password_reset_subject.txt'

    # 指定重置密码页面的模板名称(输入邮箱页面)
    template_name = "registration/password_reset_form.html"

    # 指定对邮箱进行验证的Form,默认为'PasswordResetForm',如果要实现'邮箱未注册'的提示,可以重写该Form的clean()方法
    form_class = PasswordResetCustomEmailForm


"""
属性:
template_name:指定重置密码页面的模板名称(输入邮箱页面),默认为'registration/password_reset_form.html'
form_class:指定对邮箱进行验证的Form,默认为'PasswordResetForm',如果要实现'邮箱未注册'的提示,可以重写该Form的clean()方法.
email_template_name:邮件内容的模板,默认为'registration/password_reset_email.html'.
subject_template_name:邮件主题的模板,默认'registration/password_reset_subject.txt'.
success_url:邮件发送成功(或邮箱未注册)后重定向的URL.
form_email: 发送邮件的地址.默认使用DEFAULT_FORM_EMAIL.需要在settings.py文件中进行邮箱参数的配置.
extra_context: 需要添加到模板中的额外上下文数据.
"""

"""
还有三4个页面可以还没自定义:
1. PasswordResetCustomView里的email_template_name: password_reset_email.html  
2. PasswordResetCustomView里的subject_template_name: password_reset_subject.txt  
3. 提示密码重置链接已经发送的模版password_reset_done.html
4. 提示新密码设置成功的模版password_reset_complete.html
"""


# 用户详情
class UserInfoView(View):
    # http_method_names = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserInfoView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, "users/user_info.html")


# 修改头像
class UserHeadshotView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserHeadshotView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, "users/user_headshot.html")

    def post(self, request):
        data = json.loads(request.body)
        imgBase = data.get("imgBase")
        img_b64_string = imgBase.split(",", 1)[1]  # 获取经过base64编码的jpeg图片数据
        convert_img_raw_data = base64.b64decode(img_b64_string)  # 解码得到图片的字节数据<class 'bytes'>
        photo_suffix = "jpeg"

        # 随机文件名(使用uuid + 时间戳)
        filename = "{}.{}".format(uuid.uuid4().hex[:4] + str(int(time.time() * 1000)),
                                  photo_suffix)
        # 保存文件夹的绝对路径
        folder = os.path.join(settings.MEDIA_ROOT, "avatar/%d/" % request.user.id)
        if not os.path.exists(folder):
            os.makedirs(folder)
        # 新文件的绝对路径
        dest_filename = folder + filename
        # 新建文件写入图片数据
        with open(dest_filename, "wb") as img:
            img.write(convert_img_raw_data)

        # 删除原头像文件
        user = request.user
        old_name = user.headshot.name  # 绝对路径减去( MEDIA_ROOT + \ )
        if old_name == "alien.jpg":
            # 默认的头像不要删除
            pass
        else:
            # old_abs_path = settings.MEDIA_ROOT + "/" + old_name
            old_abs_path = request.user.headshot.path  # 绝对路径
            os.remove(old_abs_path)

        # 更新头像数据
        user.headshot = "avatar/%d/" % request.user.id + filename
        user.save(update_fields=["headshot", ])
        return JsonResponse({"msg": "success"})

templates/users/register.html
{% extends "master.html" %}
{% load static %}

{% block head_css %}
    <!-- Custom styles for this template 自定义修改 -->
    <link href="/static/home/css/carousel4contact.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/home/assets/css/jumbotron-narrow.css" rel="stylesheet">

    <!-- 表单的样式 -->
    <link rel="stylesheet" href="{% static 'users/css/signin.css' %}">
{% endblock %}

{% block nav_li %}
    {{ block.super }}
{% endblock %}

{% block carousel %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-color: initial;">
            </div>
        </div>
    </div><!-- /.carousel -->
{% endblock %}

{% block wholecontents %}
    <div class="container">
        <div class="jumbotron">
            <h1>What??</h1>
            <p class="lead">还要注册</p>
        </div>

        <div class="container">
            <form class="form-signin" action="{% url 'users:register' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <h2 class="form-signin-heading">请注册</h2>
                {{ form.non_field_errors }}
                <label for="{{ form.username.id_for_label }}">姓名：</label>
                {{ form.username }}
                {{ form.username.errors }}
                <label for="{{ form.phone.id_for_label }}">手机：</label>
                {{ form.phone }}
                {{ form.phone.errors }}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <div class="checkbox">
{#                    <label>#}
{#                        <input type="checkbox" value="remember-me"> Remember me#}
{#                    </label>#}
                </div>
                <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
                <div style="margin-top: 10px">
                    已注册请<a href="{% url 'login' %}" >登录</a>
                </div>
            </form>
        </div>

        {#        {% block footer %}#}
        {#            {{ block.super }}#}
        {#        {% endblock %}#}

    </div> <!-- /container -->
{% endblock %}



{% block tail_scripts %}
{% endblock %}

templates/users/user_headshot.html
{% extends "master.html" %}
{% load static %}

{% block head_css %}
    <!-- Custom styles for this template 自定义修改 -->
    <link href="/static/home/css/carousel4contact.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/home/assets/css/jumbotron-narrow.css" rel="stylesheet">

    {#    这个样式为偷模版的时候自带的，加上后与导航栏样式有冲突， 禁用后暂未出现异样#}
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">#}

    <link rel="stylesheet" href="{% static 'users/headshot/cropper.css' %}">
    <link rel="stylesheet" href="{% static 'users/headshot/main.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{% endblock %}

{#{% block nav_li %}#}
{#{% endblock %}#}

{% block carousel %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-color: initial;">
            </div>
        </div>
    </div><!-- /.carousel -->
{% endblock %}

{% block wholecontents %}
    <!-- Content -->
    <div class="container" style="margin-top:50px;">
        <div class="row">
            <div class="col-md-9">
                <!-- <h3>Demo:</h3> -->
                <div class="img-container">
                    <img id="image" src="{{ request.user.headshot.url }}" alt="Picture">
                </div>
            </div>
            <div class="col-md-3">
                <!-- <h3>Preview:</h3> -->
                <div class="docs-preview clearfix">
                    <div class="img-preview preview-lg"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9 docs-buttons">
                <!-- <h3>Toolbar:</h3> -->

                <div class="btn-group">
                    <button type="button" class="btn btn-primary" data-method="zoom" data-option="0.1" title="Zoom In">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;zoom&quot;, 0.1)">
              放大
            </span>
                    </button>
                    <button type="button" class="btn btn-primary" data-method="zoom" data-option="-0.1"
                            title="Zoom Out">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;zoom&quot;, -0.1)">
              缩小
            </span>
                    </button>
                </div>

                <div class="btn-group">
                    <button type="button" class="btn btn-primary" data-method="move" data-option="-10"
                            data-second-option="0" title="Move Left">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;move&quot;, -10, 0)">
              左移
            </span>
                    </button>
                    <button type="button" class="btn btn-primary" data-method="move" data-option="10"
                            data-second-option="0"
                            title="Move Right">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;move&quot;, 10, 0)">
              右移
            </span>
                    </button>
                    <button type="button" class="btn btn-primary" data-method="move" data-option="0"
                            data-second-option="-10" title="Move Up">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;move&quot;, 0, -10)">
              上移
            </span>
                    </button>
                    <button type="button" class="btn btn-primary" data-method="move" data-option="0"
                            data-second-option="10"
                            title="Move Down">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;move&quot;, 0, 10)">
              下移
            </span>
                    </button>
                </div>

                <div class="btn-group">
                    <button type="button" class="btn btn-primary" data-method="rotate" data-option="-90"
                            title="Rotate Left">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;rotate&quot;, -90)">
              左转90º
            </span>
                    </button>
                    <button type="button" class="btn btn-primary" data-method="rotate" data-option="90"
                            title="Rotate Right">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;rotate&quot;, 90)">
              右转90º
            </span>
                    </button>
                </div>

                <div class="btn-group">
                    <button type="button" class="btn btn-primary" data-method="reset" title="Reset">
            <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                  title="$().cropper(&quot;reset&quot;)">
              刷新
            </span>
                    </button>
                    <label class="btn btn-primary btn-upload" for="inputImage" title="Upload image file">
                        <input type="file" class="sr-only" id="inputImage" name="file"
                               accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
                        <span class="docs-tooltip" data-toggle="tooltip" data-animation="false"
                              title="Import image with Blob URLs">
              上传图片
            </span>
                    </label>
                </div>

                <div class="btn-group btn-group-crop">
                    <button class="btn btn-primary" data-method="getCroppedCanvas"
                            data-option="{ &quot;width&quot;: 180, &quot;height&quot;: 90 }" type="button">
                        上传头像
                    </button>
                </div>

                <!-- Show the cropped image in modal -->
                <div class="modal fade docs-cropped" id="getCroppedCanvasModal" aria-hidden="true"
                     aria-labelledby="getCroppedCanvasTitle" role="dialog" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="getCroppedCanvasTitle">Cropped</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body"></div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <a class="btn btn-primary" id="download" href="javascript:void(0);"
                                   download="cropped.jpg">Download</a>
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal -->
            </div><!-- /.docs-buttons -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->

    <!-- Content -->
    <div class="container">
        {% block footer %}
            {{ block.super }}
        {% endblock %}
    </div> <!-- Content End -->
{% endblock %}


{% block tail_scripts %}
    {#    master已有jquery-1.12.4.min.js 了, 禁用后暂未出现异样#}
    {#    <script src="{% static 'users/headshot/jquery.min.js' %}"></script>#}

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>#}
    <script src="{% static 'users/headshot/jquery.cookie.js' %}"></script>

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>#}
    <script src="{% static 'users/headshot/tether.min.js' %}"></script>

    {#    这个js为偷模版的时候自带的，但是master已有bootstrap-3.3.7.min.js， 禁用后暂未出现异样#}
    {#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>#}

    <script src="{% static 'users/headshot/cropper.js' %}"></script>
    <script src="{% static 'users/headshot/main.js' %}"></script>
{% endblock %}

templates/users/user_info.html
{% extends "master.html" %}

{% block head_css %}
    <!-- Custom styles for this template 自定义修改 -->
    <link href="/static/home/css/carousel4contact.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/home/assets/css/jumbotron-narrow.css" rel="stylesheet">
{% endblock %}

{#{% block nav_li %}#}
{#{% endblock %}#}

{% block carousel %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-color: initial;">
            </div>
        </div>
    </div><!-- /.carousel -->
{% endblock %}

{% block wholecontents %}
    <div class="container">
        <div class="jumbotron" style="opacity: 0.7">
            <h1>个人详情</h1>
            <p class="lead">下面是一堆个人隐私</p>
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
                <h4>登录名</h4>
                <p>{{ request.user.username }}</p>

                <h4>手机</h4>
                <p>{{ request.user.phone }}</p>

                <h4>邮箱</h4>
                <p>{% if request.user.email %}{{ request.user.email }}{% else %}无{% endif %}</p>
            </div>

            <div class="col-lg-6">
                <h4></h4>
                <h4>注册时间</h4>
                <p>{{ request.user.created_time }}</p>

                <h4>上次登录</h4>
                <p>{{ request.user.last_login }}</p>
            </div>
        </div>
    </div> <!-- /container -->

    <!-- Content -->
    <div class="container">
        {% block footer %}
            {{ block.super }}
        {% endblock %}
    </div> <!-- Content End -->

{% endblock %}


{% block tail_scripts %}
{% endblock %}